# First we run a container to copy config file to local
# docker run -dit --name grafana grafana
# docker cp grafana:/etc/grafana/grafana.ini
# also do it for prometheus and pushgateway

version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - /etc/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    volumes:
      - /etc/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - prometheus
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    hostname: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - prometheus
# version: '3.8' #Run node exporter in each server that you want to monitor
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    hostname: node_exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/host'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100
    networks:
      - prometheus

networks:
  prometheus: