- name: Set timezone to UTC
  timezone:
    name: Etc/UTC

- name: Set hostname
  command: hostnamectl set-hostname {{ inventory_hostname }}

- name: Remove symlink resolve.conf | Comment this task if you live in outside of Iran :)
  file:
    path: "/etc/resolv.conf"
    state: absent
  ignore_errors: true

- name: Configure resolv.conf | Comment this task if you live in outside of Iran :)
  template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    mode: "0644"
  when: use_iran == "true"

- name: Add hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1 {{ inventory_hostname }} localhost"
    owner: root
    group: root
    mode: 0644

- name: Add hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.0.1 {{ inventory_hostname }} localhost"
    owner: root
    group: root
    mode: 0644

- name: Install necessary tools
  apt:
    update_cache: true
    name:
      - vim
      - sudo
      - wget
      - curl
    state: latest
    update_cache: true


- name: Copy issue.net to remote servers
  copy:
    src: issue.net
    dest: /etc/issue.net

- name: Ensure SSHD config is correct
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Banner'
    line: 'Banner /etc/issue.net'
  notify: restart sshd

- name: Copy MOTD to remote servers
  copy:
    src: motd
    dest: /etc/motd
