version: '3.9'

services:
  redis:
    container_name: redis-1
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /redis/logs:/var/log
      - /redis/d–∞ta:/root/redis
      - /redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16