---
- name: Create Directory
  ansible.builtin.file:
    path: "{{ prod_src_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ prod_src_dir_owner }}"
    group: "{{ prod_src_dir_owner }}"

- name: Print "{{ playbook_dir }}"
  debug:
    msg: The directory is "{{ playbook_dir }}"

- name: Synchronize entire repository to remote
  ansible.posix.synchronize:
    src: "{{ prod_runner_src_dir }}"
    dest: "{{ prod_src_dir }}"
    delete: true
    rsync_opts:
      - "--exclude=.env"
      - "--exclude=storage"

- name: Change directory owner
  ansible.builtin.file:
    path: "{{ prod_src_dir }}"
    state: directory
    mode: '0755'
    recurse: yes
    owner: "{{ prod_src_dir_owner }}"
    group: "{{ prod_src_dir_owner }}"

- name: Run build_script.sh on server
  shell:
    cmd: bash "{{ prod_src_dir }}"/build_script.sh